name: chatter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_ui_auth: ^1.16.1
  flutter_localizations:
    sdk: flutter
  firebase_ui_localizations: ^1.13.1
  cloud_firestore: ^5.6.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
